{
  :name => ENV['USER'] || ENV['USERNAME'],
  :gardener => [
    :six_realms,
    :six_realms,
    :six_realms,
    :six_realms,
    :phosphorus_slash,
    :phosphorus_slash,
    :phosphorus_slash,
    :phosphorus_slash,
    :mhp,
    :mhp,
  ],
  :magician => [
    :stardust_missle,
    :stardust_missle,
    :stardust_missle,
    :stardust_missle,
    :magic_dust,
    :magic_dust,
    :magic_dust,
    :magic_dust,
    :mhp,
    :mhp,
  ],
  :time_maid => [
    :mysterious_jack,
    :mysterious_jack,
    :mysterious_jack,
    :mysterious_jack,
    :changeling_magic,
    :changeling_magic,
    :changeling_magic,
    :changeling_magic,
    :mhp,
    :mhp,
  ],
  :doll_manipulator => [
    :doll_placement,
    :doll_placement,
    :doll_placement,
    :doll_placement,
    :edo,
    :edo,
    :edo,
    :edo,
    :mhp,
    :mhp
  ],
}